name: Deploy
# on:
#     push:
#         branches: [ master ]
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout

              uses: actions/checkout@v2

            - name: Deployment

              uses: appleboy/ssh-action@master

              with:

                  host: ${{ secrets.SSH_HOST }}

                  key: ${{ secrets.SSH_PRIVATE_KEY }}

                  username: ${{ secrets.SSH_USERNAME }}

                  script: |

                      cd /var/www/api.sensehair.nl/html/

                      git checkout master

                      git pull origin master

                      composer install

                      sudo php artisan config:clear
                      sudo php artisan cache:clear

                      sudo chmod -R 777 storage/ bootstrap/cache

